# Generated by Django 2.2 on 2020-07-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KintoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=100)),
                ('bui', models.CharField(choices=[('nume', '胸筋'), ('ashi', '脚'), ('nito', '二頭'), ('santo', '三頭'), ('kata', '肩'), ('hara', '腹筋'), ('senaka', '背中')], max_length=50)),
                ('kaisu', models.IntegerField()),
                ('setsu', models.IntegerField()),
            ],
        ),
    ]
